# Generated by Django 3.2.20 on 2023-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_account', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('goal', models.FloatField()),
                ('expected_year', models.IntegerField()),
            ],
        ),
    ]
