# Generated by Django 3.2.20 on 2023-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pouch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pouch',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pouch',
            name='expected_year',
        ),
        migrations.AddField(
            model_name='pouch',
            name='expected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouch',
            name='name',
            field=models.CharField(default='john', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouch',
            name='need',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouch',
            name='type_pouch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
