# Generated by Django 3.2.20 on 2023-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pouch', '0002_auto_20230729_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouch',
            name='saving',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouch',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
